version: "3.8"
services:
  db:
    build: ./db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
  web:
    build: ./web
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}  
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure
